const K='smartTodo.v3';
const defaults={tasks:[{id:1,title:'Complete DBMS assignment',space:'College',minutes:60,emoji:'🎓',important:true,done:false},{id:2,title:'Review Python notes',space:'Homework',minutes:30,emoji:'📚',important:false,done:false},{id:3,title:'Plan Smart To-Do project',space:'Projects',minutes:45,emoji:'💻',important:true,done:false}],spaces:[{name:'College',emoji:'🎓'},{name:'Homework',emoji:'📚'},{name:'Projects',emoji:'💻'},{name:'Personal',emoji:'🏠'},{name:'Kitchen',emoji:'🍳'},{name:'Fitness',emoji:'🏃'},{name:'Shopping',emoji:'🛒'},{name:'Travel',emoji:'✈️'}],focus:0,dark:false};
let S=JSON.parse(localStorage.getItem(K)||'null')||defaults;
let fid=null,interval=null,left=3600,total=3600,running=false,notified={};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const save=()=>localStorage.setItem(K,JSON.stringify(S));
const mins=m=>m>=60?`${Math.floor(m/60)}h ${m%60?m%60+'m':''}`:`${m}m`;
const pct=()=>S.tasks.length?Math.round(S.tasks.filter(t=>t.done).length/S.tasks.length*100):0;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const spaceEmoji=n=>(S.spaces.find(s=>s.name===n)?.emoji)||'📝';

function go(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.v===v));$('#side').classList.remove('open');}
window.go=go;
$$('nav button').forEach(b=>b.onclick=()=>go(b.dataset.v));
$('#menu').onclick=()=>$('#side').classList.toggle('open');

function row(t){return `<div class="task ${t.done?'done':''}" data-id="${t.id}"><input class="done" type="checkbox" ${t.done?'checked':''} aria-label="Complete task"><span class="te">${esc(t.emoji||spaceEmoji(t.space))}</span><div class="tm"><div class="tn">${esc(t.title)}</div><div class="taskmeta">${esc(t.space)} · ${mins(+t.minutes||0)}</div></div><button class="star ${t.important?'important':''}" title="${t.important?'Remove important':'Pin important'}">${t.important?'⭐':'☆'}</button><button class="del" title="Delete">×</button></div>`}
function bind(el){if(!el)return;el.onclick=e=>{const r=e.target.closest('.task');if(!r)return;const t=S.tasks.find(x=>String(x.id)===r.dataset.id);if(!t)return;if(e.target.classList.contains('done')){t.done=e.target.checked;if(t.done)celebrate()}else if(e.target.classList.contains('star')){t.important=!t.important;toast(t.important?'⭐ Marked important':'Important removed')}else if(e.target.classList.contains('del')){S.tasks=S.tasks.filter(x=>x!==t);if(fid===t.id){fid=null;stopFocus('stopped')}}else{select(t.id);return}render()}}

function render(){
 const p=pct(),done=S.tasks.filter(t=>t.done).length;
 $('#sp').textContent=p+'%';$('#bar').style.width=p+'%';$('#stotal').textContent=S.tasks.length;$('#sdone').textContent=done;$('#sfocus').textContent=mins(S.focus);$('#spercent').textContent=p+'%';$('#rp').textContent=p+'%';$('#legend').textContent=`${done} completed · ${S.tasks.length-done} remaining`;$('#ring').style.background=`conic-gradient(var(--a) ${p*3.6}deg,var(--s2) 0)`;
 const active=S.tasks.filter(t=>!t.done);$('#homeTasks').innerHTML=active.slice(0,5).map(row).join('')||'<p class="muted">🎉 All clear! Add a task.</p>';bind($('#homeTasks'));
 const imp=S.tasks.filter(t=>t.important&&!t.done).slice(0,3);$('#important').innerHTML=imp.map(t=>`<div class="imp"><span>${esc(t.emoji||spaceEmoji(t.space))}</span><div><b>${esc(t.title)}</b><small>${esc(t.space)} · ${mins(+t.minutes)}</small></div></div>`).join('')||'<div class="imp">✨ <div><b>No pinned tasks</b><small>Pin something important</small></div></div>';
 const q=($('#search')?.value||'').toLowerCase(),f=$('#filter')?.value||'all',st=$('#status')?.value||'all';
 const list=S.tasks.filter(t=>(!q||t.title.toLowerCase().includes(q)||t.space.toLowerCase().includes(q))&&(f==='all'||t.space===f)&&(st==='all'||(st==='active'&&!t.done)||(st==='done'&&t.done)||(st==='important'&&t.important)));
 $('#allTasks').innerHTML=list.map(row).join('')||'<div class="card"><p>No matching tasks.</p></div>';bind($('#allTasks'));
 const oldFilter=$('#filter').value;$('#filter').innerHTML='<option value="all">All spaces</option>'+S.spaces.map(s=>`<option value="${esc(s.name)}">${esc(s.emoji)} ${esc(s.name)}</option>`).join('');$('#filter').value=S.spaces.some(s=>s.name===oldFilter)?oldFilter:'all';
 $('#space').innerHTML=S.spaces.map(s=>`<option value="${esc(s.name)}">${esc(s.emoji)} ${esc(s.name)}</option>`).join('');updateEmojiPreview();
 $('#spacesGrid').innerHTML=S.spaces.map(s=>{const a=S.tasks.filter(t=>t.space===s.name),d=a.filter(t=>t.done).length,pp=a.length?d/a.length*100:0;return `<div class="space"><span class="ico">${esc(s.emoji)}</span><h3>${esc(s.name)}</h3><p>${d} completed · ${a.length-d} remaining</p><div class="track"><i style="width:${pp}%"></i></div><button class="secondary" onclick="openSpace('${esc(s.name)}')">Open space</button></div>`}).join('');
 const ft=S.tasks.filter(t=>!t.done);$('#focusTasks').innerHTML=ft.map(row).join('')||'<p class="muted">No active tasks.</p>';bind($('#focusTasks'));save();
}
window.openSpace=n=>{go('tasks');$('#filter').value=n;render()};

function openModal(){ $('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');$('#task').focus();updateEmojiPreview(); }
function closeModal(){ $('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');$('#form').reset();if(S.spaces.length)$('#space').value=S.spaces[0].name;updateEmojiPreview(); }
window.openModal=openModal;window.closeModal=closeModal;
$('#addTop').onclick=openModal;$('#closeModal').onclick=closeModal;
$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#modal').classList.contains('open'))closeModal()});
function updateEmojiPreview(){const s=$('#space')?.value;const em=spaceEmoji(s);if($('#emojiPreview'))$('#emojiPreview').textContent=`${em} Emoji is automatic for ${s||'this space'}`}
$('#space').onchange=updateEmojiPreview;
$('#form').onsubmit=e=>{e.preventDefault();const title=$('#task').value.trim();if(!title)return;const space=$('#space').value||'Personal';S.tasks.unshift({id:Date.now()+Math.random(),title,space,minutes:Math.max(1,+$('#minutes').value||30),emoji:spaceEmoji(space),important:$('#important').checked,done:false});closeModal();render();toast('Task added ✦');go('tasks')};

$('#search').oninput=render;$('#filter').onchange=render;$('#status').onchange=render;
$('#theme').onclick=()=>{S.dark=!S.dark;document.body.classList.toggle('dark',S.dark);$('#theme').textContent=S.dark?'☀ Light mode':'☾ Dark mode';save()};
if(S.dark){document.body.classList.add('dark');$('#theme').textContent='☀ Light mode'}
$('#newSpace').onclick=()=>{const n=prompt('Space name, e.g. Exam or Fitness');if(!n?.trim())return;const name=n.trim();if(S.spaces.some(x=>x.name.toLowerCase()===name.toLowerCase()))return toast('Space already exists');const suggested={Fitness:'🏃',Shopping:'🛒',Travel:'✈️',College:'🎓',Homework:'📚',Projects:'💻',Personal:'🏠',Kitchen:'🍳'}[name]||'✨';S.spaces.push({name,emoji:suggested});render();toast(`${name} space created with ${suggested}`)};

function select(id){fid=id;const t=S.tasks.find(x=>x.id==id);if(!t)return;$('#ftitle').textContent=t.title;$('#fmeta').textContent=`${t.space} · ${mins(+t.minutes)}`;go('focus');setTimer()}
function setTimer(){clearInterval(interval);interval=null;running=false;const v=$('#preset').value,m=v==='custom'?(+$('#custom').value||60):+v;total=left=m*60;notified={};$('#pause').disabled=true;$('#pause').textContent='Pause';$('#start').textContent='Start focus';ui();$('#tstate').textContent='ready'}
$('#preset').onchange=()=>{$('#custom').hidden=$('#preset').value!=='custom';if(!running)setTimer()};$('#custom').oninput=()=>{if(!running)setTimer()};
function ui(){const m=Math.floor(left/60),s=left%60;$('#clock').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timer').style.background=`conic-gradient(#2dd4bf ${(left/Math.max(total,1))*360}deg,#2b5558 0)`}
function stopFocus(status='stopped',reset=true){clearInterval(interval);interval=null;running=false;if(reset)left=total;$('#pause').disabled=true;$('#pause').textContent='Pause';$('#start').textContent='Start focus';$('#tstate').textContent=status;ui()}
function tick(){left=Math.max(0,left-1);ui();const m=Math.ceil(left/60);[30,20,10,5,1].forEach(x=>{const cb=$(`[data-m="${x}"]`);if(m===x&&!notified[x]&&cb?.checked){notified[x]=1;toast(`⏰ ${x} minute${x>1?'s':''} remaining`)}});if(left<=0){clearInterval(interval);interval=null;running=false;$('#pause').disabled=true;$('#pause').textContent='Pause';$('#start').textContent='Start focus';$('#tstate').textContent='time’s up';toast("⏰ Time's up!");celebrate();}}
$('#start').onclick=()=>{if(!fid){const t=S.tasks.find(x=>!x.done);if(t){select(t.id)}else return toast('Add an active task first')}if(!running){if($('#tstate').textContent==='stopped'||$('#tstate').textContent==='completed'||$('#tstate').textContent==='time’s up'||left===total)setTimer();running=true;$('#pause').disabled=false;$('#start').textContent='Running';$('#tstate').textContent='focused';clearInterval(interval);interval=setInterval(tick,1000);toast('Focus session started 🎯')}};
$('#pause').onclick=()=>{if(!running){running=true;$('#pause').textContent='Pause';$('#tstate').textContent='focused';clearInterval(interval);interval=setInterval(tick,1000)}else{running=false;clearInterval(interval);$('#pause').textContent='Resume';$('#tstate').textContent='paused';$('#start').textContent='Running'}};
$('#stop').onclick=()=>{stopFocus('stopped',true);toast('Focus session stopped and reset')};
$('#complete').onclick=()=>{if(!fid)return toast('Choose a task first');const t=S.tasks.find(x=>x.id==fid);if(t){const used=Math.max(0,total-left);t.done=true;S.focus+=Math.round(used/60);stopFocus('completed',true);celebrate();render();toast('Focus task completed 🎉')}};

function addMsg(t,c){const d=document.createElement('div');d.className='msg '+c;d.innerHTML=esc(t).replace(/\n/g,'<br>');$('#messages').appendChild(d);$('#messages').scrollTop=$('#messages').scrollHeight}
function addTaskCard(t){const d=document.createElement('div');d.className='msg bot task-suggestion';const task={...t,emoji:t.emoji||spaceEmoji(t.space||'Personal')};d.innerHTML=`<b>${esc(task.emoji)} ${esc(task.title||'New task')}</b><br><small>${esc(task.space||'Personal')} · ${Math.max(1,+task.minutes||30)} min${task.priority?' · '+esc(task.priority)+' priority':''}</small> <button class="link ai-add">＋ Add</button>`;d.querySelector('.ai-add').onclick=()=>{addSuggestedTask(task);d.querySelector('.ai-add').textContent='✓ Added';d.querySelector('.ai-add').disabled=true};$('#messages').appendChild(d)}
function addSuggestedTask(t){const space=S.spaces.some(s=>s.name===t.space)?t.space:'Personal';S.tasks.unshift({id:Date.now()+Math.random(),title:String(t.title||'New task'),space,minutes:Math.max(1,+t.minutes||30),emoji:spaceEmoji(space),important:String(t.priority||'').toLowerCase()==='high',done:false});render();toast('AI task added ✦')}
function addAll(tasks){(tasks||[]).forEach(t=>addSuggestedTask(t));toast(`${tasks.length} AI task${tasks.length===1?'':'s'} added ✦`)}
function showAIResult(data){if(data.reply)addMsg(data.reply,'bot');const tasks=Array.isArray(data.tasks)?data.tasks:[];if(tasks.length){const wrap=document.createElement('div');wrap.className='msg bot';wrap.innerHTML=`<b>Suggested tasks</b> <button class="link add-all">＋ Add all</button>`;wrap.querySelector('.add-all').onclick=()=>{addAll(tasks);wrap.querySelector('.add-all').disabled=true;wrap.querySelector('.add-all').textContent='✓ Added all'};$('#messages').appendChild(wrap);tasks.forEach(addTaskCard)}if(data.table){const d=document.createElement('div');d.className='msg bot';d.innerHTML=`<b>📊 Structured plan</b><pre>${esc(data.table)}</pre>`;$('#messages').appendChild(d)}$('#messages').scrollTop=$('#messages').scrollHeight}
function localPlanner(message){const l=message.toLowerCase();const active=S.tasks.filter(t=>!t.done);if(/help me plan tomorrow|plan tomorrow|tomorrow/.test(l)){const reply=active.length?`Sure. For tomorrow, I would start with your highest-priority active task, then move to the next important task, and leave lighter work for later. You currently have ${active.length} active task${active.length===1?'':'s'}. If you tell me your available hours, I can turn this into a time-blocked plan.`:'Sure. Tell me what you need to accomplish tomorrow and how many hours you have available, and I can build a realistic schedule.';return {reply,tasks:[],table:''}}
if(/what should i do first|priorit|dbms|python|study/.test(l)){const space=S.spaces.some(s=>s.name==='College')?'College':'Personal';return {reply:'I would start with the most urgent or high-impact academic work, then use shorter sessions for practice and revision.',tasks:[{title:'Review the main concepts',space,minutes:35,emoji:'📚',priority:'high'},{title:'Practice questions',space,minutes:45,emoji:'📝',priority:'medium'},{title:'Review mistakes and weak areas',space,minutes:30,emoji:'🔎',priority:'medium'},{title:'Do a short final revision',space,minutes:20,emoji:'🔁',priority:'medium'}],table:''}}
if(/project|app|website/.test(l))return {reply:'I can break the project into practical stages such as requirements, implementation, testing, and polish. If you share the project goal, I can make the steps specific.',tasks:[],table:''};
return {reply:'I can help with planning, prioritization, explanations, schedules, or turning a clear plan into tasks. Tell me what you are trying to accomplish and I will work through it with you.',tasks:[],table:''}}
const sessionId='session-'+Math.random().toString(36).slice(2);let aiOnline=false;
async function askAI(text){const context={spaces:S.spaces.map(s=>s.name),tasks:S.tasks.filter(t=>!t.done).slice(0,30).map(t=>({title:t.title,space:t.space,minutes:t.minutes,important:t.important}))};const res=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,session_id:sessionId,context})});if(!res.ok)throw new Error('AI request failed');return await res.json()}
async function send(){const x=$('#chat').value.trim();if(!x)return;addMsg(x,'user');$('#chat').value='';const wait=document.createElement('div');wait.className='msg bot typing';wait.textContent='Thinking…';$('#messages').appendChild(wait);$('#messages').scrollTop=$('#messages').scrollHeight;try{const data=await askAI(x);wait.remove();showAIResult(data);$('#aiStatus').textContent='● AI online';$('#aiStatus').classList.add('online');aiOnline=true}catch(err){wait.remove();aiOnline=false;$('#aiStatus').textContent='● AI offline · local planner';$('#aiStatus').classList.remove('online');showAIResult(localPlanner(x));addMsg('Live AI is offline, so I answered with the local planner. Start the Python server and configure your API key to use full AI reasoning.','bot')}}
$('#send').onclick=send;$('#chat').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$$('.chips button').forEach(b=>b.onclick=()=>{$('#chat').value=b.textContent;send()});
$$('.tools button').forEach(b=>b.onclick=()=>{const p=b.dataset.p;$('#chat').value=p==='study'?'Make a practical study plan for my current college tasks.':p==='project'?'Break my project into practical development and testing steps.':'Help me build a realistic routine for tomorrow.';send()});

$('#toTasks').onclick=()=>{const raw=$('#tin').value.trim();if(!raw)return toast('Paste rows first');const ls=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const looksHeader=/task|title/i.test(ls[0])&&/space/i.test(ls[0]);const rows=looksHeader?ls.slice(1):ls;let added=0;rows.forEach(l=>{const c=l.split(/[,|\t]/).map(x=>x.trim().replace(/^"|"$/g,''));if(c[0]){const space=S.spaces.some(s=>s.name===c[1])?c[1]:'Personal';S.tasks.unshift({id:Date.now()+Math.random(),title:c[0],space,minutes:+c[2]||30,emoji:spaceEmoji(space),important:false,done:false});added++}});render();toast(`${added} task${added===1?'':'s'} imported`)};

function updateTableButton(){const has=$('#tableTasks').value.trim();$('#toTable').disabled=!has}$('#tableTasks').oninput=updateTableButton;
$('#toTable').onclick=()=>{const raw=$('#tableTasks').value.trim();if(!raw)return toast('Enter at least one task first');const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const rows=lines.map((line,i)=>{let c=line.split(/\t|\|/).map(x=>x.trim()).filter(Boolean);if(c.length===1)c=line.split(/,\s*/).map(x=>x.trim()).filter(Boolean);const title=c[0];const space=S.spaces.some(s=>s.name.toLowerCase()===String(c[1]||'').toLowerCase())?S.spaces.find(s=>s.name.toLowerCase()===String(c[1]||'').toLowerCase()).name:'Personal';const minutes=Number(c[2])||30;return `"${title.replaceAll('"','""')}","${space}",${minutes}`});$('#tout').value=['Task,Space,Minutes',...rows].join('\n');toast(`${lines.length} task${lines.length===1?'':'s'} converted to table`)};
$('#copy').onclick=async()=>{const v=$('#tout').value;if(!v)return toast('Generate a table first');try{await navigator.clipboard.writeText(v);toast('Table copied')}catch{toast('Copy failed — select the table text manually')}};

let imageFile=null,ocrTasks=[];
$('#image').onchange=e=>{imageFile=e.target.files[0];if(!imageFile)return;const u=URL.createObjectURL(imageFile);$('#preview').innerHTML=`<img src="${u}" alt="Uploaded task list">`;$('#ocrResult').textContent='Image ready. Click “Extract tasks from image”.';$('#ocrBtn').disabled=false;$('#addOcr').hidden=true};
function cleanOcrLines(text){const banned=/^(college tasks?|tasks?|to[- ]?do|checklist|you can do it!?|today'?s tasks?|my tasks?|todo list|task list)$/i;const raw=text.split(/\r?\n/).map(x=>x.replace(/[|]+/g,' ').replace(/^\s*[-•*]+\s*/, '').replace(/^\s*\d+[.)]\s*/, '').trim()).filter(Boolean);const out=[];for(const line of raw){const normalized=line.replace(/\s+/g,' ').trim();if(normalized.length<4||banned.test(normalized)||/^[^a-zA-Z0-9]+$/.test(normalized))continue;if(out.some(x=>x.toLowerCase()===normalized.toLowerCase()))continue;out.push(normalized)}return out.slice(0,20)}
async function extractImageWithAI(file){const fd=new FormData();fd.append('image',file);const res=await fetch('/api/image-tasks',{method:'POST',body:fd});if(!res.ok)throw new Error('vision unavailable');return await res.json()}
$('#ocrBtn').onclick=async()=>{if(!imageFile)return;$('#ocrBtn').disabled=true;$('#ocrBtn').textContent='Analyzing image…';$('#ocrResult').textContent='Reading the actual task items. Please wait.';try{let result=null;try{result=await extractImageWithAI(imageFile)}catch(e){}if(result?.tasks?.length){ocrTasks=result.tasks.map(t=>({title:t.title,space:S.spaces.some(s=>s.name===t.space)?t.space:'Personal',minutes:+t.minutes||30,emoji:spaceEmoji(t.space),important:false}));$('#ocrResult').textContent=ocrTasks.map(x=>'• '+x.title).join('\n');toast(`${ocrTasks.length} task${ocrTasks.length===1?'':'s'} detected`)}else{const r=await Tesseract.recognize(imageFile,'eng',{logger:m=>{if(m.status==='recognizing text')$('#ocrResult').textContent=`Reading image… ${Math.round((m.progress||0)*100)}%`}});const lines=cleanOcrLines(r.data.text||'');ocrTasks=lines.map(title=>({title,space:'Personal',minutes:30,emoji:'📝',important:false}));$('#ocrResult').textContent=ocrTasks.length?ocrTasks.map(x=>'• '+x.title).join('\n'):'No clear task lines were detected. Try a sharper image.';toast(ocrTasks.length?`${ocrTasks.length} possible tasks found`:'No tasks detected')}$('#addOcr').hidden=!ocrTasks.length}catch(e){$('#ocrResult').textContent='Image analysis failed. Try a clearer image or run the Python server with AI enabled.';toast('Image analysis failed')}finally{$('#ocrBtn').disabled=false;$('#ocrBtn').textContent='Extract tasks from image'}};
$('#addOcr').onclick=()=>{ocrTasks.forEach(addSuggestedTask);$('#addOcr').hidden=true;toast('Extracted tasks added ✦')};

async function checkAI(){try{const r=await fetch('/api/health');if(!r.ok)throw new Error();const d=await r.json();if(d.ai){$('#aiStatus').textContent=`● AI online · ${d.model}`;$('#aiStatus').classList.add('online');$('#assistantMode').textContent='Live AI planning mode';aiOnline=true}else{$('#aiStatus').textContent='● Server ready · API key needed';$('#assistantMode').textContent='Backend ready — add your API key for live AI'}}catch{$('#aiStatus').textContent='● Local planner';$('#assistantMode').textContent='Open through the Python server for live AI'}}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2200)}
function celebrate(){for(let i=0;i<18;i++){const d=document.createElement('i');d.style.cssText=`position:fixed;left:50%;top:45%;width:8px;height:13px;background:${['#14b8a6','#f59e0b','#8b5cf6','#ef4444'][i%4]};z-index:100;transform:translate(${(Math.random()-.5)*600}px,${(Math.random()-.5)*400}px) rotate(${Math.random()*360}deg);transition:1s`;document.body.appendChild(d);setTimeout(()=>d.remove(),900)}}

const now=new Date();$('#date').textContent=now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});const h=now.getHours();$('#greet').innerHTML=`Good ${h<12?'morning':h<18?'afternoon':'evening'}, Fahima <span style="color:#5eead4">✦</span>`;render();setTimer();updateTableButton();checkAI();
